config/routes.rb
Pblog::Application.routes.draw do
  
  # posts
  resources :posts

  # sessions
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  # users
  controller :users do
    post 'users' => :create
    get 'profile' => :profile
    get 'signup' => :new
    get 'super_delete' => :super_delete
  end

  root 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :subject, :date, :user, presence: true

  belongs_to :user

  after_initialize { self.date ||= DateTime.current }
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :storage => :dropbox,
                    :dropbox_credentials => Rails.root.join("config/dropbox.yml")

  def author
    user.name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :email, presence: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }

  validate :only_one_user
  before_save { email.downcase! }

  has_secure_password

  has_many :posts, dependent: :destroy

  private
  def only_one_user
    errors[:base] << "You can't register more then one user!" unless User.count.zero?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authorize

  protected

  def authorize
    unless User.find_by(id: session[:user_id])
      # todo: redirect -> root_url когда будет список материалов доступных неавторизованным пользователям
      redirect_to login_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :authorize, only: :index
  before_filter :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.page(params[:page]).per(5)
  end

  def new
    @post = Post.new    
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = 'Post save success!'
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      flash[:success] = 'Post edit success!'
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Post destroyed!'
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :subject, :date, :photo)
    end

    def find_post
      @post = current_user.posts.find(params[:id])
    end

    def current_user
      User.find_by(id: session[:user_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize

  def new
    if User.find_by(id: session[:user_id])
      redirect_to profile_url
    end
  end

  def create
    if params[:email].blank? || params[:password].blank?
      flash[:error] = 'Fill all fields, please!'
      redirect_to login_url
    else
      user = User.find_by(email: params[:email])
      if user and user.authenticate(params[:password])
        session[:user_id] = user.id
        flash[:notice] = "Hello, dear #{user.name}!"
        redirect_to root_url
      else
        flash[:error] = 'Invalid email and password combination'
        redirect_to login_url
      end  
    end 
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Good bye!'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize, only: [:new, :create]

  def new
    redirect_to profile_path unless User.count.zero?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Hello, dear #{@user.name}!"    
      redirect_to profile_path
    else
      render 'new'
    end
  end

  def profile
    @user = User.first
    @posts = @user.posts.order("date DESC")
  end

  def super_delete
    User.destroy_all
    session[:user_id] = nil
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_link_to(label, path, options={})
    content_tag('li', link_to(label, path, options), class: (current_page?(path) ? "active" : nil))
  end

  def link_to_login_or_signup
    if User.count.zero?
      current_link_to 'Sign up', signup_path
    else
      current_link_to 'Login', login_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.slim
ul class='nav nav-pills'
  li = current_link_to "Home", root_path
  - if session[:user_id].present?
    li = current_link_to "Profile", profile_path 
    li = current_link_to "Sign out", logout_path, method: "delete"
  - else
    li = link_to_login_or_signup

app/views/layouts/application.html.slim
doctype html
html
  head
    title = "Personal Blog"
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    /[if lt IE 9] script src="http://html5shim.googlecode.com/svn/trunk/html5.js"
  body
    div class="container"
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      = render 'layouts/header' 
      = yield

app/views/posts/_form.html.slim
= form_for @post, html: { multipart: true } do |f|
  = render partial: 'shared/errors', locals: { obj: @post }
  = f.label :title, 'Title'
  = f.text_field :title
  = f.label :subject, 'Subject'
  = f.text_area :subject
  = f.label :photo
  = f.file_field :photo
  
  .field
    = f.submit class: 'btn btn-success btn-standart'
    = link_to 'Back', :back, class: 'btn btn-info btn-standart'

app/views/posts/_new.html.slim
.row
  = render 'form'

app/views/posts/_new_post.html.slim
= link_to "New post", new_post_path, class: 'btn btn-info btn-standart'

app/views/posts/_post.html.slim
h2 = post.title
p = simple_format(post.subject)
- if post.photo.exists?
  = image_tag post.photo.url(:thumb)
p = post.date
p = post.author

app/views/posts/_post_in_profile.html.slim
h2 = post.title
p = simple_format(post.subject)

= link_to 'Edit', edit_post_path(post), class: 'btn btn-warning btn-standart'
= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-standart'

app/views/posts/edit.html.slim
h1 Edit post

.row
  = render 'form'

app/views/posts/index.html.slim
h1 Posts

= paginate @posts
= render @posts

app/views/posts/new.html.slim
= render "new"

app/views/posts/show.html.slim
h2 = @post.title

p 
  = simple_format(@post.subject)
p = "Date: #{@post.date}"
p = "Author: #{@post.author}"

app/views/shared/_errors.html.slim
- if obj.errors.any? 
  #error_explanation
    div class="alert alert-error"
      ul
        - obj.errors.full_messages.each do |msg| 
          li = msg

app/views/users/new.html.slim
.row
  div class="span6 offset3"
    h1 Sign up

    = form_for @user do |f|
      = render partial: 'shared/errors', locals: { obj: @user }

      .field
        = f.label :name
        = f.text_field :name
      .field
        = f.label :email
        = f.text_field :email
      .field
        = f.label :password
        = f.password_field :password

        = f.label :password_confirmation, "Confirmation"
        = f.password_field :password_confirmation

      = f.submit "Create my account", class: 'btn btn-info btn-standart'

app/views/users/profile.html.slim
.row
  h1 Profile

  #new-post
    = render "posts/new_post"

  #posts-list
    = render partial: 'posts/post_in_profile', collection: @posts, as: :post

  hr
  = link_to 'Delete user!', super_delete_path, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-standart'